drop database WorldOfDarknessTest;
create database WorldOfDarknessTest;
use WorldOfDarknessTest;
CREATE TABLE `character` (  `characterID` int(11) NOT NULL AUTO_INCREMENT,  `firstName` varchar(20) NOT NULL,  `middleName` varchar(20) DEFAULT NULL,  `lastName` varchar(20) DEFAULT NULL,  `unspentExperience` int(11) NOT NULL,  `approved` tinyint(1) NOT NULL,  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  `user_id` int(11) NOT NULL,  PRIMARY KEY (`characterID`),  KEY `character_user` (`user_id`));
CREATE TABLE `characterTraits` (  `character` int(11) NOT NULL,  `trait` int(11) NOT NULL,  `currentRank` int(11) NOT NULL DEFAULT '0',  `description` varchar(20) NOT NULL,  `firstSpecialty` varchar(50) DEFAULT NULL,  `scondSpecialty` varchar(50) DEFAULT NULL,  `currentLevel` int(11) NOT NULL DEFAULT '0' COMMENT 'this will be enforced by the software to not exceed the max level for the given trait.',  PRIMARY KEY (`character`,`trait`),  KEY `characterTraits_Traits` (`trait`));
CREATE TABLE `critter` (  `critterID` int(11) NOT NULL AUTO_INCREMENT,  `critterName` varchar(100) NOT NULL,  `implemented` tinyint(1) NOT NULL,  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`critterID`)) COMMENT='Human, vampire, Changeling ect...';
CREATE TABLE `role` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `userID` int(11) NOT NULL,  `roleName` varchar(100) NOT NULL DEFAULT 'player',  `userName` varchar(100) NOT NULL,  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  KEY `Roles_user` (`userID`));
CREATE TABLE `subCritter` (  `subCritterID` int(11) NOT NULL AUTO_INCREMENT,  `subCritterLabel` varchar(20) NOT NULL COMMENT 'this will be Kith if the subCritter is pooka for example',  `critterID` int(11) NOT NULL,  `critterSubName` varchar(20) NOT NULL COMMENT 'Pooka, Gangrel, Get of Fenris ect..',  `firstAdvantage` blob NOT NULL,  `secondAdvantage` blob NOT NULL,  `flaw` blob NOT NULL,  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`subCritterID`),  KEY `subCritter_critter` (`critterID`)) COMMENT='Vampire : clan Werewolf: tribe, auspice, breed Changeling: Kith, seeming, house mage: tradition/convention Wraith ???';
CREATE TABLE `trait` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `openToCritterID` int(11) DEFAULT '0',  `goodAtSubCritterID` int(11) DEFAULT NULL,  `traitName` varchar(100) NOT NULL,  `specialtyAllowed` tinyint(1) NOT NULL DEFAULT '1',  `minimumScore` int(11) NOT NULL DEFAULT '0' COMMENT 'For traits that have no score, like a garou gift, this will be 0',  `maximumScore` int(11) NOT NULL DEFAULT '5' COMMENT 'For traits that have no score, like a garou gift, this will be 0.',  `traitType` varchar(50) NOT NULL COMMENT 'This is the kind of trait it is.  E: Art, realm, discipline, Talent, background ect...',  `newCost` int(11) NOT NULL COMMENT 'This is the cost to buy the first dot in a trait.  For a background it will always be 0.  For things that only have 1 level, it will be the cost t0 buy it',  `cheapCost` int(11) NOT NULL COMMENT 'this is the cost to raise something if you are ''''good at it''''  clan disciplines for example.',  `normalCost` int(11) NOT NULL COMMENT 'this is the cost to buy something on average.  For situations like orphans and spheres, it will be the cost to buy all spheres.',  `expensiveCost` int(11) NOT NULL COMMENT 'this is the cost to buy something that you are not the best at.  Non primary spheres, non clan disciplines for examples.',  `freebieCost` int(11) NOT NULL COMMENT 'This is the cost to buy something with freebie points.',  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  KEY `Traits_critter` (`openToCritterID`),  KEY `Traits_subCritter` (`goodAtSubCritterID`));
CREATE TABLE `user` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `firstName` varchar(20) NOT NULL,  `lastName` varchar(20) NOT NULL,  `userName` varchar(100) NOT NULL COMMENT 'This must also be unique in the database.',  `authenticator` varchar(256) NOT NULL,  `EmailAddress` varchar(100) NOT NULL, `phoneNumber` char(13) DEFAULT NULL,  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`));
ALTER TABLE `character` ADD CONSTRAINT  `character_user`  FOREIGN KEY (`user_id`) REFERENCES `user` (`id`);
ALTER TABLE `characterTraits` ADD CONSTRAINT `characterTraits_character` FOREIGN KEY (`character`) REFERENCES `character` (`characterID`);
ALTER TABLE `role` ADD CONSTRAINT `Roles_user` FOREIGN KEY (`userID`) REFERENCES `user` (`id`);
ALTER TABLE `subCritter` ADD CONSTRAINT `subCritter_critter` FOREIGN KEY (`critterID`) REFERENCES `critter` (`critterID`);
ALTER TABLE `characterTraits` ADD CONSTRAINT `characterTraits_Traits` FOREIGN KEY (`trait`) REFERENCES `trait` (`id`);
ALTER TABLE `trait` ADD CONSTRAINT `Traits_critter` FOREIGN KEY (`openToCritterID`) REFERENCES `critter` (`critterID`);
ALTER TABLE `trait` ADD CONSTRAINT `Traits_subCritter` FOREIGN KEY (`goodAtSubCritterID`) REFERENCES `subCritter` (`subCritterID`);
INSERT INTO user (firstName, lastName, userName, authenticator, emailAddress, phoneNumber) VALUES ('Ducky', 'Powers', 'negaduck', 'PASSW0RD', 'yousuck@Irule.com','512-555-1212');
INSERT INTO user (firstName, lastName, userName, authenticator, emailAddress, phoneNumber) VALUES ('Jodie', 'Whittaker', 'theDoctor', 'TheSonic', 'theDoctor@gallifray.gov','161-803-3988');
INSERT INTO user (firstName, lastName, userName, authenticator, emailAddress, phoneNumber) VALUES ('Richard', 'Boone', 'Paladin', 'nidalaP', 'Paladin@CarlotonHotel.com','888-GET-HELP');
INSERT INTO user (firstName, lastName, userName, authenticator, emailAddress, phoneNumber, isDeleted) VALUES ('Kent', 'Allard', 'TheShadow', 'TheShadowKnows', 'lamontCranston@cranstonInternational.com','512-555-1212', 1);
INSERT INTO user (firstName, lastName, userName, authenticator, emailAddress, phoneNumber) VALUES ('Drake', 'Mallard', 'totallyNotDarkwingDuck', 'PASSW0RD', 'IAMAWESOME@Irule.com','512-555-1212');
INSERT INTO critter (critterName, implemented) VALUES ('Human',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Vampire',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Wereworlf',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Mage',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Changeling',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Wraith',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Mummy',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Bygone',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Exalted',FALSE);
INSERT INTO critter (critterName, implemented) VALUES ('Dragon',FALSE);
INSERT INTO role (userID, roleName, userName) VALUES (1, 'Nerf Herder', 'Negaduck');
INSERT INTO role (userID, roleName, userName) VALUES (1, 'The Villain', 'Negaduck');
INSERT INTO role (userID, roleName, userName) VALUES (2, 'The token Female', 'theDoctor');
INSERT INTO role (userID, roleName, userName, isDeleted) VALUES (5, 'The Terror that Flaps', 'totallyNotDarkwingDuck', 1);
